### ISSUE TITLE
Truncated docs page?

### ISSUE THREAD

**Issue by alreadydone** [leanprover-community/mathlib4_docs#1]
[This mathlib4 docs page](https://leanprover-community.github.io/mathlib4_docs/Mathlib/AlgebraicGeometry/ProjectiveSpectrum/Scheme.html) seems broken; the [source](https://github.com/leanprover-community/mathlib4/blob/71bf59b2e096ba9b061fa65665c5cd32170da014/Mathlib/AlgebraicGeometry/ProjectiveSpectrum/Scheme.lean) is much longer than just three declarations. Compare [mathlib3 docs](https://leanprover-community.github.io/mathlib_docs/algebraic_geometry/projective_spectrum/scheme.html).

**Comment by eric-wieser** [comment]
@alreadydone, please re-open this against doc-gen4
